export const SEED_PROPERTIES = [
  {
    id: "prop-1",
    title: "The Solis Cliffside Brutalist Sanctuary",
    slug: "solis-cliffside-brutalist-sanctuary",
    refNumber: "EST-84920",
    description: "Perched atop pristine granite cliffs overlooking the Pacific, The Solis Sanctuary is a monumental triumph of sculptural concrete, floor-to-ceiling ultra-clear acoustic glazing, and private deep-water mooring. Crafted by Pritzker laureate architects, featuring cantilevered infinity pools, private subterranean gallery vault, and biometric air filtration.",
    propertyType: "Brutalist Villa",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 38500000,
    currency: "USD",
    pricePerSqm: 28102,
    bedrooms: 6,
    bathrooms: 8.5,
    livingRooms: 3,
    kitchenCount: 2,
    floor: 1,
    totalFloors: 3,
    buildingYear: 2024,
    areaSqm: 1370,
    landAreaSqm: 5400,
    parkingSpaces: 6,
    country: "United States",
    city: "Big Sur",
    district: "Pacific Coastline",
    address: "704 Highway 1, Big Sur Reserve, CA",
    latitude: 36.2704,
    longitude: -121.8081,
    postalCode: "93920",
    featured: true,
    verified: true,
    viewsCount: 14200,
    favoritesCount: 384,
    heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_VEasvn44zxHvit6O03KiBxy1S05Jd7GuMERiYJ9dwBkrxs4F3YisKmox9H3PSQNlY7nxr4IwcFHodvlTfndO0sbworx3JiGfdRxUhSMQutkDCEiTdNvn5V_tqAkyW-kqe1IHviRZ9d_0F29H0nf-CEst-3VE8aK8cY7XYGDxo5Oci-67rpRmn5r763WpXYgdz0HFPXhcmnXojt77OihedBvehSSjI45BPokZyX-ZSFbBoOEg37cInw",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "Cantilevered Infinity Pool", category: "Wellness" },
      { name: "Private Helipad Node", category: "Aviation" },
      { name: "Subterranean Art Vault", category: "Security" },
      { name: "Wine Cave & Tasting Salon", category: "Culinary" },
      { name: "Full Home Automation / Lutron", category: "Technology" },
      { name: "Oceanfront Meditation Terrace", category: "Outdoor" },
    ],
  },
  {
    id: "prop-2",
    title: "Palais de la Rive Waterfront Estate",
    slug: "palais-de-la-rive-waterfront-estate",
    refNumber: "EST-91042",
    description: "An extraordinary private domain on the golden shores of Lake Geneva with private deep-draft yacht harbor, restored 19th-century salon architecture blended with modern minimalist pavilion extensions, and panoramic views of Mont Blanc.",
    propertyType: "Waterfront Compound",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 52000000,
    currency: "USD",
    pricePerSqm: 32500,
    bedrooms: 8,
    bathrooms: 11,
    livingRooms: 4,
    kitchenCount: 3,
    floor: 1,
    totalFloors: 3,
    buildingYear: 2023,
    areaSqm: 1600,
    landAreaSqm: 12000,
    parkingSpaces: 10,
    country: "Switzerland",
    city: "Geneva",
    district: "Cologny",
    address: "Route de la Capite 118, Cologny, Geneva",
    latitude: 46.2167,
    longitude: 6.1833,
    postalCode: "1223",
    featured: true,
    verified: true,
    viewsCount: 21900,
    favoritesCount: 612,
    heroImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "Private Yacht Harbor & Boathouse", category: "Nautical" },
      { name: "Indoor Thermal Swimming Pavilion", category: "Wellness" },
      { name: "Staff Quarters & Security Compound", category: "Operations" },
      { name: "Formal English Parterre Gardens", category: "Landscape" },
    ],
  },
  {
    id: "prop-3",
    title: "The Sky Pavilion Crown Duplex",
    slug: "the-sky-pavilion-crown-duplex",
    refNumber: "EST-47219",
    description: "Crowning the topmost two levels of an iconic Tribeca cast-iron residential tower, featuring 24-foot soaring ceilings, private 360-degree landscaped wrap-around observatory terrace, private elevator foyer, and bespoke Boffi chef kitchen.",
    propertyType: "Penthouse & Duplex",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 24500000,
    currency: "USD",
    pricePerSqm: 31818,
    bedrooms: 4,
    bathrooms: 5.5,
    livingRooms: 2,
    kitchenCount: 1,
    floor: 58,
    totalFloors: 60,
    buildingYear: 2024,
    areaSqm: 770,
    parkingSpaces: 3,
    country: "United States",
    city: "New York",
    district: "Tribeca",
    address: "56 Leonard Street, Penthouse 58, New York, NY",
    latitude: 40.7176,
    longitude: -74.0069,
    postalCode: "10013",
    featured: true,
    verified: true,
    viewsCount: 18400,
    favoritesCount: 520,
    heroImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "360° Wrap-around Sky Observatory", category: "Views" },
      { name: "Dedicated Private Elevator Access", category: "Access" },
      { name: "Bespoke Onyx Fireplace Centerpiece", category: "Design" },
      { name: "Valet & 24/7 Concierge Service", category: "Service" },
    ],
  },
  {
    id: "prop-4",
    title: "Arashiyama Sukiya Bamboo Sanctuary",
    slug: "arashiyama-sukiya-bamboo-sanctuary",
    refNumber: "EST-33018",
    description: "An ultra-rare private retreat secluded within Kyoto's historic Arashiyama district. Blending centuries-old Sukiya-zukuri carpentry with geothermal underfloor heating, natural hot spring onsen, and private stroll garden bordering ancient bamboo groves.",
    propertyType: "Historic Palazzo",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 18800000,
    currency: "USD",
    pricePerSqm: 25753,
    bedrooms: 5,
    bathrooms: 6,
    livingRooms: 2,
    kitchenCount: 1,
    floor: 1,
    totalFloors: 2,
    buildingYear: 2022,
    areaSqm: 730,
    landAreaSqm: 3800,
    parkingSpaces: 4,
    country: "Japan",
    city: "Kyoto",
    district: "Ukyo-ku",
    address: "Sagatenryuji, Ukyo Ward, Kyoto",
    latitude: 35.0163,
    longitude: 135.6713,
    postalCode: "616-8385",
    featured: false,
    verified: true,
    viewsCount: 9800,
    favoritesCount: 310,
    heroImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "Natural Geothermal Onsen Bath", category: "Wellness" },
      { name: "Traditional Chashitsu Tea Pavilion", category: "Culture" },
      { name: "Protected Bamboo Grove Vista", category: "Nature" },
      { name: "Hinoki Wood Architectural Finishes", category: "Design" },
    ],
  },
  {
    id: "prop-5",
    title: "The Mayfair Sovereign Townhouse",
    slug: "the-mayfair-sovereign-townhouse",
    refNumber: "EST-66129",
    description: "Grade II listed Georgian trophy residence situated on Grosvenor Square. Complete state-of-the-art restorative overhaul including passenger lift to all 6 levels, double-height basement pool and spa, car lift, and private courtyard terrace.",
    propertyType: "Townhouse",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 44000000,
    currency: "USD",
    pricePerSqm: 37931,
    bedrooms: 7,
    bathrooms: 9,
    livingRooms: 4,
    kitchenCount: 2,
    floor: 1,
    totalFloors: 6,
    buildingYear: 2023,
    areaSqm: 1160,
    parkingSpaces: 3,
    country: "United Kingdom",
    city: "London",
    district: "Mayfair",
    address: "24 Grosvenor Square, Mayfair, London",
    latitude: 51.5115,
    longitude: -0.1517,
    postalCode: "W1K 6LG",
    featured: true,
    verified: true,
    viewsCount: 16500,
    favoritesCount: 442,
    heroImage: "https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "Subterranean 15m Swimming Pool", category: "Wellness" },
      { name: "Automated Hydraulic Car Lift", category: "Automotive" },
      { name: "Private Passenger Lift (All Floors)", category: "Access" },
      { name: "Staff Mews Apartment", category: "Staff" },
    ],
  },
  {
    id: "prop-6",
    title: "Alpine Ridge Private Chalet",
    slug: "alpine-ridge-private-chalet",
    refNumber: "EST-11923",
    description: "Ski-in/ski-out architectural masterpiece located on the prestigious Sunnegga slopes of Zermatt, with direct unimpeded views of the iconic Matterhorn. Built from aged alpine larch and Valser quartzite with private wellness spa, ski salon, and outdoor heated pool.",
    propertyType: "Alpine Chalets",
    listingType: "FOR_SALE" as const,
    status: "PUBLISHED" as const,
    price: 29000000,
    currency: "USD",
    pricePerSqm: 32954,
    bedrooms: 6,
    bathrooms: 7,
    livingRooms: 2,
    kitchenCount: 1,
    floor: 1,
    totalFloors: 4,
    buildingYear: 2024,
    areaSqm: 880,
    landAreaSqm: 1800,
    parkingSpaces: 4,
    country: "Switzerland",
    city: "Zermatt",
    district: "Sunnegga",
    address: "Riedweg 45, 3920 Zermatt",
    latitude: 46.0207,
    longitude: 7.7491,
    postalCode: "3920",
    featured: false,
    verified: true,
    viewsCount: 13100,
    favoritesCount: 388,
    heroImage: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
    ],
    amenities: [
      { name: "Ski-in / Ski-out Direct Access", category: "Skiing" },
      { name: "Matterhorn Unobstructed Vista", category: "Views" },
      { name: "Outdoor Heated Hot Springs Pool", category: "Wellness" },
      { name: "Custom Boot Warming & Equipment Lounge", category: "Sports" },
    ],
  },
];

export const SEED_AGENTS = [
  {
    id: "agent-1",
    name: "Kenjiro Takahashi",
    email: "k.takahashi@estatepro-reserve.io",
    title: "Managing Partner, Asia-Pacific Private Client Group",
    agency: "Sotheby's Sovereign Capital Partner",
    officeLocation: "Tokyo Central & Geneva",
    rating: 4.98,
    reviewCount: 42,
    grossMandateBook: 148500000,
    activeMandates: 14,
    experienceYears: 18,
    tierBadge: "Tier 1 Node",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    specializations: "Ultra-HNW Cross-Border Acquisitions, Historic Assets, Japan Trophy Tier",
  },
  {
    id: "agent-2",
    name: "Vance Sterling",
    email: "v.sterling@estatepro-reserve.io",
    title: "Senior Private Advisor • European Escrow Lead",
    agency: "Christie's International Private Reserve",
    officeLocation: "Geneva & Zurich",
    rating: 4.95,
    reviewCount: 38,
    grossMandateBook: 210000000,
    activeMandates: 19,
    experienceYears: 15,
    tierBadge: "Tier 1 Node",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    specializations: "Waterfront Compounds, Private Islands, Alpine Chalets",
  },
  {
    id: "agent-3",
    name: "Eleanor Vance-Roche",
    email: "e.vance@estatepro-reserve.io",
    title: "Executive Director • North American Trophy Portfolios",
    agency: "Knight Frank Sovereign Guild",
    officeLocation: "New York & Miami",
    rating: 4.99,
    reviewCount: 56,
    grossMandateBook: 320000000,
    activeMandates: 22,
    experienceYears: 20,
    tierBadge: "Tier 1 Node",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    specializations: "Tribeca Penthouses, Palm Beach Mansions, Hamptons Compounds",
  },
];

export const SEED_LEADS = [
  {
    id: "lead-1",
    name: "Baroness Helene von Habsburg",
    email: "h.habsburg@habsburg-capital.at",
    phone: "+43 1 512 8840",
    stage: "QUALIFIED" as const,
    score: 96,
    source: "Zurich Private Bank Referral",
    budget: 45000000,
    netWorth: "> $150M",
    notes: "Seeking trophy lakeside residence on Lake Geneva with private yacht dock. AML/KYC pre-cleared by UBS Sovereign Desk.",
    createdAt: "2026-03-01T10:30:00Z",
  },
  {
    id: "lead-2",
    name: "Maximilian Chen",
    email: "m.chen@apex-singapore.sg",
    phone: "+65 6789 1234",
    stage: "VIEWING_SCHEDULED" as const,
    score: 92,
    source: "Singapore Family Office Association",
    budget: 28000000,
    netWorth: "> $80M",
    notes: "VIP Helicopter transfer requested for Tribeca Sky Pavilion on Friday.",
    createdAt: "2026-03-03T14:15:00Z",
  },
  {
    id: "lead-3",
    name: "Sheikh Tariq Al-Maktoum",
    email: "tariq.office@maktoum-invest.ae",
    phone: "+971 4 360 9900",
    stage: "NEGOTIATION" as const,
    score: 99,
    source: "Direct Sovereign Mandate",
    budget: 65000000,
    netWorth: "> $500M",
    notes: "Formal Letter of Intent submitted for Solis Sanctuary. Title deed escrow underway.",
    createdAt: "2026-02-28T09:00:00Z",
  },
  {
    id: "lead-4",
    name: "Sir James Sterling-Clarke",
    email: "clarke@sterling-partners.co.uk",
    phone: "+44 20 7946 0192",
    stage: "OFFER_SUBMITTED" as const,
    score: 94,
    source: "London Private Wealth Forum",
    budget: 48000000,
    netWorth: "> $120M",
    notes: "Terms sheet in final review for Mayfair Townhouse.",
    createdAt: "2026-03-02T16:45:00Z",
  },
  {
    id: "lead-5",
    name: "Dr. Arthur Pendelton",
    email: "pendelton@geneva-biotech.ch",
    phone: "+41 22 700 8812",
    stage: "NEW" as const,
    score: 84,
    source: "EstatePro Private Reserve Inquiry",
    budget: 15000000,
    netWorth: "> $40M",
    notes: "Interested in Alpine Ridge Chalet in Zermatt.",
    createdAt: "2026-03-05T11:20:00Z",
  },
];

export const SEED_MONOGRAPHS = [
  {
    id: "mono-1",
    title: "The Architecture of Sovereignty: Capital Flight into Trophy Real Estate",
    slug: "the-architecture-of-sovereignty-capital-flight-trophy-real-estate",
    category: "Capital Intelligence",
    volume: "Volume IV",
    subtitle: "Global Ultra-Prime Real Estate Telemetry & Macro Reallocation 2026",
    summary: "An in-depth empirical audit of cross-border institutional and family office capital reallocations into prime trophy real estate across Switzerland, Tokyo, London, and New York.",
    content: "Over the past 24 months, geopolitical uncertainty and macroeconomic volatility have accelerated the transition of sovereign capital into tangible, unencumbered prime architectural assets...",
    coverImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=85",
    publishedAt: "2026-02-15",
  },
  {
    id: "mono-2",
    title: "Alpine Reserves & Safe-Haven Havens: The Zermatt & St. Moritz Report",
    slug: "alpine-reserves-safe-haven-havens-zermatt-st-moritz",
    category: "Market Monograph",
    volume: "Volume IV",
    subtitle: "Analyzing Valuations and Strict Lex Koller Regulations in High-Altitude Sanctuaries",
    summary: "Reviewing trophy chalet supply deficits and the unprecedented premium commanded by unobstructed Matterhorn vistas and ski-in/ski-out infrastructure.",
    content: "Supply in top-tier Swiss alpine enclaves remains structurally constrained due to stringent zoning regulations and foreign national purchase caps...",
    coverImage: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=85",
    publishedAt: "2026-02-28",
  },
];
