import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#141313",
        "surface-dim": "#141313",
        "surface-lowest": "#0a0a0a",
        "surface-base": "#141313",
        "surface-card": "#1c1b1b",
        "surface-container-lowest": "#0f0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2b2a2a",
        "surface-container-highest": "#363434",
        "surface-elevated": "#201f1f",
        "surface-bright": "#3a3939",
        "surface-variant": "#363434",
        "surface-tint": "#c6c6c7",
        "surface-overlay": "#2a2a2a",
        primary: "#ffffff",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "inverse-primary": "#5d5f5f",
        secondary: "#c7c6c6",
        "on-secondary": "#303031",
        "secondary-container": "#464747",
        "on-secondary-container": "#b6b5b5",
        "secondary-fixed": "#e3e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        tertiary: "#ffffff",
        "on-tertiary": "#313030",
        "tertiary-container": "#e5e2e1",
        "on-tertiary-container": "#656463",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474746",
        background: "#141313",
        "on-background": "#e6e1e1",
        "on-surface": "#e6e1e1",
        "on-surface-variant": "#c4c7c8",
        "inverse-surface": "#e6e1e1",
        "inverse-on-surface": "#323030",
        outline: "#8e9192",
        "outline-variant": "#444748",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "border-hairline": "#444748",
        "status-verified": "#27c93f",
        "status-rent": "#98c379",
        "status-pending": "#ffbd2e",
        "status-error": "#ff5f56",
        "status-sale": "#ffffff",
        "chart-accent": "#61afef",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "2rem",
        "container-max": "75rem",
        "card-padding-lg": "2rem",
        "gutter-mobile": "1.25rem",
        "section-gap": "7.5rem",
        base: "0.5rem",
        "card-padding-sm": "1.25rem",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Manrope", "sans-serif"],
        serif: ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "display-xl": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "headline-lg": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "headline-md": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "headline-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "micro-meta": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["4.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["2.5rem", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["1.875rem", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["2rem", { lineHeight: "1.3", letterSpacing: "normal", fontWeight: "400" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "normal", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "normal", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.4", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.08em", fontWeight: "600" }],
        "micro-meta": ["0.625rem", { lineHeight: "1.3", letterSpacing: "0.15em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
